// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCVv4KbpZHNG74pedtOCrjzAhETrq9CAE',
    appId: '1:435561902539:web:68698b5f69733fe869064e',
    messagingSenderId: '435561902539',
    projectId: 'cadastro-de-usuarios-cd0f8',
    authDomain: 'cadastro-de-usuarios-cd0f8.firebaseapp.com',
    storageBucket: 'cadastro-de-usuarios-cd0f8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtOLaymbCy89DxYQ3HF54e7A9wOs5dLVo',
    appId: '1:435561902539:android:4b01445db50b6d5169064e',
    messagingSenderId: '435561902539',
    projectId: 'cadastro-de-usuarios-cd0f8',
    storageBucket: 'cadastro-de-usuarios-cd0f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQICvwWmdxyEEbyqeuvk_XtuDSK-j2ras',
    appId: '1:435561902539:ios:fd4672785f36985669064e',
    messagingSenderId: '435561902539',
    projectId: 'cadastro-de-usuarios-cd0f8',
    storageBucket: 'cadastro-de-usuarios-cd0f8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQICvwWmdxyEEbyqeuvk_XtuDSK-j2ras',
    appId: '1:435561902539:ios:fd4672785f36985669064e',
    messagingSenderId: '435561902539',
    projectId: 'cadastro-de-usuarios-cd0f8',
    storageBucket: 'cadastro-de-usuarios-cd0f8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCVv4KbpZHNG74pedtOCrjzAhETrq9CAE',
    appId: '1:435561902539:web:acfa5e4e5d05c54b69064e',
    messagingSenderId: '435561902539',
    projectId: 'cadastro-de-usuarios-cd0f8',
    authDomain: 'cadastro-de-usuarios-cd0f8.firebaseapp.com',
    storageBucket: 'cadastro-de-usuarios-cd0f8.firebasestorage.app',
  );

}